### ISSUE TITLE
How to obtain the speed in Table 2?

### ISSUE THREAD

**Issue by inspirelt** [ma-xu/pointMLP-pytorch#10]
Hi, 

thanks for the excellent job. I'm confusing on how to obtain the speed in Table 2. For pointMLPElite, I set the test batch_size = 16,  and it takes 5s to process the whole 2468 test samples(~494samples/s). With test batch_size=1, it takes about 24s -> ~103samples/s. Both results are far different from the 176samples/s in Table 2. Would you mind explaining the speedtest operation in details?

**Comment by ma-xu** [comment]
Hi @inspirelt ,

Thanks for your interest.

I tested all methods using the first option.  
I just uploaded the tested time results here [pointmlp time](https://drive.google.com/drive/folders/1Ne6hqgpqDtC3fy1oiXaBLOpFAeWU9iPW?usp=sharing) , [point-elite time](https://drive.google.com/drive/folders/15Xs80qAr_iHMF_TYCuQNvcaU2NS30U9u?usp=sharing). The testing times are 22s/ 14s (See out.txt file),respectively. Hence, the speed would be 112samples/s and 176samples/s.  Please ignore the model name because it was the name of our developing version.

I guess the difference comes from the machines. Note we are tested on one **Tesla V100-
pcie GPU** and 4 cores AMD EPYC 7351 2.60GHz CPU.

Please let me know if any further questions.

**Comment by inspirelt** [comment]
Thanks for your reply.
