### ISSUE TITLE
Use without CUDA?

### ISSUE THREAD

**Issue by simon-at-hypothetic** [ma-xu/pointMLP-pytorch#34]
Hello! 
Would it be possible to use your code without the need of CUDA?

**Comment by ma-xu** [comment]
@simon-at-hypothetic 
Sure, You can siply call the defined farthest_point_sample function instead of furthest_point_sample in pointnet2_ops lib.
Here is a simple example (tested, works but will be slower):
https://web.northeastern.edu/smilelab/xuma/pointMLP/pointmlp_nocuda.py

Please let me know if you have any further questions.

**Comment by simon-at-hypothetic** [comment]
thats great, the code you shared worked for me, thanks!
