### ISSUE TITLE
what takes advance in using 'from pointnet2_ops import pointnet2_utils'

### ISSUE THREAD

**Issue by Yukimori-GitHub** [ma-xu/pointMLP-pytorch#63]
I noticed that u have achieved the part of 'farthest_point_sample' by function, but in your repo, u are using pointnet2_utils.furthest_point_sample(xyz, self.groups).long() instead of that function.
I am new coming to the research of point cloud, so I have this question. Why u use this lib but that achieved function?

By the way, why I have this question because I ran this code and found that I could not do the fps.
out = _ext.furthest_point_sampling(xyz, npoint)
RuntimeError: false INTERNAL ASSERT FAILED at "pointnet2_ops/_ext-src/src/sampling.cpp":83, please report a bug to PyTorch. CPU not supported
Do u know how to fix it?

It is very enough to answer the first question. If u could answer those, plz update me anytime and I will appreciate u with many thanks!

**Comment by ma-xu** [comment]
1. using pointnet2_utils.furthest_point_sample can achieve faster speed since it operations on CUDA.
2. The reason is that you did not install the cuda lib. Install the lib will fix this problem.

For your development, you can simply uncomment line 160
https://github.com/ma-xu/pointMLP-pytorch/blob/b5dcf4d0ca2085d10fe1dc5e6f2972cddec8399d/classification_ScanObjectNN/models/pointmlp.py#L160
and comment line 161
https://github.com/ma-xu/pointMLP-pytorch/blob/b5dcf4d0ca2085d10fe1dc5e6f2972cddec8399d/classification_ScanObjectNN/models/pointmlp.py#L161
to run codes on cpu (I would not suggest training like this due to slow speed).

**Comment by Yukimori-GitHub** [comment]
Inspire me a lot for your reply with much information. Thank u!

**Comment by Yukimori-GitHub** [comment]
Back to the paper, how to plot out the 'Loss landscape' like figure 4?

**Comment by ma-xu** [comment]
@Yukimori-GitHub See here: https://github.com/ma-xu/pointMLP-pytorch/issues/42#issuecomment-1153547400

**Comment by Yukimori-GitHub** [comment]
Ok, yes. And now I have a new question, how can I get the information about the train/test speed like table 2?

**Comment by ma-xu** [comment]
@Yukimori-GitHub See here: https://github.com/ma-xu/pointMLP-pytorch/issues/10  and https://github.com/ma-xu/pointMLP-pytorch/issues/40

**Comment by Yukimori-GitHub** [comment]
thanks!
